name: Build Redmi Note 7 Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: kp7742/kernel_build_action@main
      with:
          kernel-url: https://github.com/ImSpiDy/kernel_xiaomi_lavender
          kernel-branch: "14-Retro"
          config: lavender_defconfig
          arch: arm64
          android-version: 12
          aosp-clang: true
          aosp-clang-version: r416183b1
          ksu: true
          ksu-version: v0.9.5
          ksu-lkm: false
          python-27: true
          anykernel3: true
